changeLogFile=db/changelog/db.changelog-master.xml
url=jdbc:postgresql://localhost:5434/skill_exchange_db
username=skill_admin
password=skill_password
driver=org.postgresql.Driver
classpath=drivers/postgresql-42.7.9.jar